### ISSUE TITLE
Error: [$injector:unpr] Unknown provider: appSettingsProvider <- appSettings <- productResource

### ISSUE THREAD

**Issue by MustVf333** [DeborahK/AngularF2BWebAPI#11]
I am having an issue with the above error. Following the course from the beginning and struck at CORS and Formatters.

**Comment by portal7** [comment]
me too!

**Comment by SagarManjunath** [comment]
same issue here

**Comment by DeborahK** [comment]
This is most often caused by one of several things:

1) The angular.module is not defined appropriately.
```
(function () {
    "use strict";

    angular
        .module("common.services")
        .factory("productResource",
                ["$resource",
                 "appSettings",
                    productResource])
}());

```
2) You are missing the entry in the index.htm file.

```
    <!-- Services -->
    <script src="common/common.services.js"></script>
    <script src="common/productResource.js"></script>
```

3) There is a casing problem with productResource somewhere in the application. Ensure that all references to the service follow the same casing.
